#
# Special Thanks to Author
# https://www.serverlessops.io/blog/static-websites-on-aws-s3-with-serverless-framework

service: serverless-XXXXXXXX

frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs12.x

plugins:
  - serverless-s3-sync


custom:
  siteName: XXXXXXXXX
  aliasHostedZoneId: XXXXXXXXXXXX
  aliasDNSName: XXXXXXXXXXXXXX
  s3Sync:
    - bucketName: ${self:custom.siteName}
      localDir: static

resources:

  Resources:

    StaticSite:
      Type: AWS::S3::Bucket
      Properties:
        AccessControl: PublicRead
        BucketName: ${self:custom.siteName}
        WebsiteConfiguration:
          IndexDocument: index.html

    StaticSiteS3BucketPolicy:
      Type: AWS::S3::BucketPolicy
      Properties:
        Bucket:
          Ref: StaticSite
        PolicyDocument:
          Statement:
            - Sid: PublicReadGetObject
              Effect: Allow
              Principal: "*"
              Action:
                - s3:GetObject
              Resource:
                Fn::Join: [
                    "", [
                      "arn:aws:s3:::",
                    {
                      "Ref": "StaticSite"
                    },
                      "/*"
                  ]
                ]

#    DnsRecord:
#      Type: "AWS::Route53::RecordSet"
#      Properties:
#        AliasTarget:
#          DNSName: ${self:custom.aliasDNSName}
#          HostedZoneId: ${self:custom.aliasHostedZoneId}
#        HostedZoneName: ${self:custom.siteName}.
#        Name:
#          Ref: StaticSite
#        Type: 'A'